sudo: required
services:
  - docker
before_install:
  - docker build -t ajmaradiaga/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ajmaradiaga/react-test npm test -- --coverage

after_success:
  - docker build -t ajmaradiaga/ob-client ./client
  - docker build -t ajmaradiaga/ob-server ./server
  - docker build -t ajmaradiaga/ob-worker ./worker
  - docker build -t ajmaradiaga/ob-nginx ./nginx
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ajmaradiaga/ob-client
  - docker push ajmaradiaga/ob-server
  - docker push ajmaradiaga/ob-worker
  - docker push ajmaradiaga/ob-nginx

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-west-1"
  name: "octo-brocoli"
  env: "OctoBrocoli-Env"
  bucket_name: "elasticbeanstalk-eu-west-1-899085916962"
  bucket_path: "octo-brocoli"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

language: generic
